### ISSUE TITLE
无法签到

### ISSUE THREAD

**Issue by BJAny** [marigold233/lenovo-sign#14]
```
2023-01-02 07:00:04,334 - INFO: 134*** ck为空，重新获取ck并保存
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0xffffab590a00>, 'Connection to reg.lenovo.com.cn timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='reg.lenovo.com.cn', port=443): Max retries exceeded with url: /auth/rebuildleid (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffffab590a00>, 'Connection to reg.lenovo.com.cn timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/lenovo-sign/lenovo_sign.py", line 219, in <module>
    main()
  File "/opt/lenovo-sign/lenovo_sign.py", line 211, in main
    session = login(username, password)
  File "/opt/lenovo-sign/lenovo_sign.py", line 148, in login
    session = get_cookie()
  File "/opt/lenovo-sign/lenovo_sign.py", line 106, in get_cookie
    session.get(url="https://reg.lenovo.com.cn/auth/rebuildleid")
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='reg.lenovo.com.cn', port=443): Max retries exceeded with url: /auth/rebuildleid (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffffab590a00>, 'Connection to reg.lenovo.com.cn timed out. (connect timeout=None)'))
```

**Comment by marigold233** [comment]
在本地跑还是阿里云函数

**Comment by BJAny** [comment]
> 在本地跑还是阿里云函数

本地

**Comment by marigold233** [comment]
> > 在本地跑还是阿里云函数
> 
> 本地

换网络尝试

**Comment by BJAny** [comment]
尝试过了，丢在家里跑的，重播宽带新的ip也不行> > > 在本地跑还是阿里云函数
> 
> > 
> 
> > 本地
> 
> 
> 
> 换网络尝试

**Comment by BJAny** [comment]
23年之前还是一切正常的，就1号那天之后签不上了，然后rm重新clone仓库下来也是卡在获取cookie😟

**Comment by marigold233** [comment]
那你注释` lenovo_sign.py` 里面的代码，试试吧：
```python
# session.get(url="https://reg.lenovo.com.cn/auth/rebuildleid")
···

**Comment by BJAny** [comment]
```
Traceback (most recent call last):
  File "/opt/lenovo-sign/lenovo_sign.py", line 219, in <module>
    main()
  File "/opt/lenovo-sign/lenovo_sign.py", line 211, in main
    session = login(username, password)
  File "/opt/lenovo-sign/lenovo_sign.py", line 148, in login
    session = get_cookie()
  File "/opt/lenovo-sign/lenovo_sign.py", line 118, in get_cookie
    if login_response.json().get("ret") == "1":
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by BJAny** [comment]
> 那你注释` lenovo_sign.py` 里面的代码，试试吧：
> 
> ```python
> 
> # session.get(url="https://reg.lenovo.com.cn/auth/rebuildleid")
> 
> ···

还是报错

**Comment by marigold233** [comment]
我阿里云函数没有报错，或许你可以测试下云函数，或者云服务器？

**Comment by BJAny** [comment]
可能被拉黑ip段了，我稍后丢在服务器上试试

**Comment by BJAny** [comment]
使用腾讯云服务器，还是报错，python为最新3.11.1
`2023-01-04 20:07:41,657 - INFO: 134*** ck为空，重新获取ck并保存
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 248, in _get_conn
    return conn or self._new_conn()
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 816, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='reg.lenovo.com.cn', port=443): Max retries exceeded with url: /auth/rebuildleid (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/lenovo-sign/lenovo_sign.py", line 219, in <module>
    main()
  File "/opt/lenovo-sign/lenovo_sign.py", line 211, in main
    session = login(username, password)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lenovo-sign/lenovo_sign.py", line 148, in login
    session = get_cookie()
              ^^^^^^^^^^^^
  File "/opt/lenovo-sign/lenovo_sign.py", line 106, in get_cookie
    session.get(url="https://reg.lenovo.com.cn/auth/rebuildleid")
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='reg.lenovo.com.cn', port=443): Max retries exceeded with url: /auth/rebuildleid (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))`

**Comment by marigold233** [comment]
![image](https://user-images.githubusercontent.com/62014410/210564233-2ec215cc-4b7e-479b-8f97-4cafab50b727.png)
请试试这样看有无报错

**Comment by BJAny** [comment]
> ![image](https://user-images.githubusercontent.com/62014410/210564233-2ec215cc-4b7e-479b-8f97-4cafab50b727.png) 请试试这样看有无报错

![image](https://user-images.githubusercontent.com/6690619/210565854-74750c0b-c9d7-44a9-8bfc-1bd584e3ddeb.png)

**Comment by marigold233** [comment]
> > ![image](https://user-images.githubusercontent.com/62014410/210564233-2ec215cc-4b7e-479b-8f97-4cafab50b727.png) 请试试这样看有无报错
> 
> ![image](https://user-images.githubusercontent.com/6690619/210565854-74750c0b-c9d7-44a9-8bfc-1bd584e3ddeb.png)

你这是py2.7 呀，要用python3.x，终端敲python3进入python3

**Comment by BJAny** [comment]
哦我忘记了，还真有报错
![image](https://user-images.githubusercontent.com/6690619/210566860-10bfeb76-194a-4ad5-976c-b4514a05ab5c.png)

**Comment by marigold233** [comment]
> 哦我忘记了，还真有报错 ![image](https://user-images.githubusercontent.com/6690619/210566860-10bfeb76-194a-4ad5-976c-b4514a05ab5c.png)

如果你是centos系统可以试着安装openssl：
```python
yum install -y openssl-devel openssl11 openssl11-devel

```

**Comment by BJAny** [comment]
装完openssl还是报错
![image](https://user-images.githubusercontent.com/6690619/210569110-3fc6ee0c-4bbd-44ad-9050-a66d9003ae3d.png)

**Comment by BJAny** [comment]
神奇了，我的本地跑的签到又复活了
![image](https://user-images.githubusercontent.com/6690619/210569501-28fc1f60-d16e-4e7f-9a02-54972f493378.png)

**Comment by marigold233** [comment]
> 神奇了，我的本地跑的签到又复活了 ![image](https://user-images.githubusercontent.com/6690619/210569844-1de596c7-2eea-4c13-8651-98d6aa9846e0.png)

那就没毛病了，放在服务器上面跑吧

**Comment by BJAny** [comment]
> > 神奇了，我的本地跑的签到又复活了 ![image](https://user-images.githubusercontent.com/6690619/210569844-1de596c7-2eea-4c13-8651-98d6aa9846e0.png)
> 
> 
> 
> 那就没毛病了，放在服务器上面跑吧

😂腾讯云上ssl报错不折腾了，我丢在家里的小服务器跑几天看看还有没有问题，先这样吧

**Comment by marigold233** [comment]
> > > 神奇了，我的本地跑的签到又复活了 ![image](https://user-images.githubusercontent.com/6690619/210569844-1de596c7-2eea-4c13-8651-98d6aa9846e0.png)
> > 
> > 
> > 那就没毛病了，放在服务器上面跑吧
> 
> 😂腾讯云上ssl报错不折腾了，我丢在家里的小服务器跑几天看看还有没有问题，先这样吧

你这不是服务器啊，能用了就行。
服务器估计要先yum卸载之前装的openssl，然后编译安装openssl，可以参考以下文章：

- https://zhuanlan.zhihu.com/p/453788639

然后还有问题就百度"Can't connect to HTTPS URL because the SSL module is not available." 吧

**Comment by BJAny** [comment]
好的感谢，回头我看看
