### ISSUE TITLE
无法签到了，总是报错

### ISSUE THREAD

**Issue by anonymous216041** [marigold233/lenovo-sign#31]
Traceback (most recent call last):
  File "/arcadia/repo/dch0319_lenovo-sign/lenovo_sign.py", line 244, in <module>
    main()
  File "/arcadia/repo/dch0319_lenovo-sign/lenovo_sign.py", line 239, in main
    message += sign(session)
  File "/arcadia/repo/dch0319_lenovo-sign/lenovo_sign.py", line 179, in sign
    token = re.findall('token\s=\s"(.*?)"', res.text)[0]
IndexError: list index out of range

**Comment by anonymous216041** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/arcadia/repo/marigold233_lenovo-sign/lenovo_sign.py", line 244, in <module>
    main()
  File "/arcadia/repo/marigold233_lenovo-sign/lenovo_sign.py", line 239, in main
    message += sign(session)
  File "/arcadia/repo/marigold233_lenovo-sign/lenovo_sign.py", line 199, in sign
    .json()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by anonymous216041** [comment]
用的是类似青龙的Arcadia的DOCKER容器，在群晖和黑群晖，本地运行。报错

**Comment by anonymous216041** [comment]
过了元旦后开始发现这个问题，起初一天多签几次总有一次能过，现在是只要运行脚本
2024-01-05 21:54:23,606 - INFO: 133******12 ck没有错
Traceback (most recent call last):
  File "/jd/own/marigold233_lenovo-sign/lenovo_sign.py", line 244, in <module>
    main()
  File "/jd/own/marigold233_lenovo-sign/lenovo_sign.py", line 239, in main
    message += sign(session)
  File "/jd/own/marigold233_lenovo-sign/lenovo_sign.py", line 179, in sign
    token = re.findall('token\s=\s"(.*?)"', res.text)[0]
IndexError: list index out of range
就这样直接报错了，都到不了第二个账号检查

**Comment by anonymous216041** [comment]
2024-01-05 22:44:52,356 - INFO: 133*****12 ck没有错
2024-01-05 22:44:53,734 - INFO: text/html; charset=UTF-8
2024-01-05 22:44:53,734 - INFO: 500
2024-01-05 22:44:53,734 - INFO: Expecting value: line 1 column 1 (char 0)
2024-01-05 22:44:53,920 - INFO: 166*****08 ck没有错
Traceback (most recent call last):
  File "/jd/own/marigold233_lenovo-sign/lenovo_sign.py", line 244, in <module>
    main()
  File "/jd/own/marigold233_lenovo-sign/lenovo_sign.py", line 239, in main
    message += sign(session)
  File "/jd/own/marigold233_lenovo-sign/lenovo_sign.py", line 199, in sign
    .json()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

更换本地IP地址后，还是这样

**Comment by anonymous216041** [comment]
我在家里的群晖，黑群晖 openwrt 甲骨文云上都试了，都没有可以成功签到，都是类似同样的报错。求大神早日归来，搭救小弟

**Comment by marigold233** [comment]
下午我试试

**Comment by sasaju** [comment]
我也遇到了同样的报错

**Comment by earthwq** [comment]
我也遇到了同样的报错

**Comment by anonymous216041** [comment]
都是通病相连啊

**Comment by earthwq** [comment]
好象是联想服务器的问题，用浏览器访问mclub.lenovo.com.cn，登录后就出错提示500

**Comment by Lemon7ProPlus** [comment]
好像又可以了.刚刚成功了.

**Comment by anonymous216041** [comment]
2024-01-09 15:11:39,645 - INFO: 133*****6212 ck没有错
2024-01-09 15:11:41,253 - INFO: 166*****3308 ck没有错
2024-01-09 15:11:43,963 - INFO: 139*****3181 ck没有错
2024-01-09 15:11:46,388 - INFO: 180*****1015 ck为空，重新获取ck并保存
2024-01-09 15:11:49,214 - INFO: 136*****4081 ck为空，重新获取ck并保存
2024-01-09 15:11:52,056 - INFO: 133*****6202 ck为空，重新获取ck并保存
2024-01-09 15:11:54,328 - INFO: 166*****3764 ck为空，重新获取ck并保存
2024-01-09 15:11:56,724 - INFO: 173*****317 ck为空，重新获取ck并保存
2024-01-09 15:11:59,591 - INFO: 173*****0773 ck为空，重新获取ck并保存
send email error (550, b'User has no permission')
我就到这里就停了，没有继续下去

**Comment by anonymous216041** [comment]
![image](https://github.com/marigold233/lenovo-sign/assets/70944033/05becd46-d6c9-4f12-b27d-41ef5b2c0753)

**Comment by marigold233** [comment]
> ![image](https://private-user-images.githubusercontent.com/70944033/295134571-05becd46-d6c9-4f12-b27d-41ef5b2c0753.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDYxODcsIm5iZiI6MTcwNDgwNTg4NywicGF0aCI6Ii83MDk0NDAzMy8yOTUxMzQ1NzEtMDViZWNkNDYtZDZjOS00ZjEyLWIyN2QtNDFlZjViMmMwNzUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEzMTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzY1MzFhNmM4NDMwMjU0NDhkMDk2YjBlZGJhYzY2OWNkNTFjYWVlMmFmNmJlNTY5ZDA0NjE2MTQyOGY2MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X-KF_DjSBY1fIaCk4awlCzCYmh0-Q2sr2li3RcDzGso)

看看你配置

**Comment by marigold233** [comment]
又可以了兄弟们，服务器是不是抽风了

**Comment by sasaju** [comment]
确实，麻烦作者大大了

**Comment by marigold233** [comment]
> 确实，麻烦作者大大了

每天建议签到两三次，实时通知搞上

**Comment by sasaju** [comment]
> > 确实，麻烦作者大大了
> 
> 每天建议签到两三次，实时通知搞上

好的，感谢提醒~

**Comment by anonymous216041** [comment]
我这边还是不行，几台机器都没成功过

**Comment by anonymous216041** [comment]
@Arcadia CLI ➜  /arcadia # task run /arcadia/repo/marigold233_lenovo-sign/lenovo_sign.py
2024-01-10 07:12:50,924 - INFO: 13312 ck没有错
2024-01-10 07:13:29,441 - INFO: 1608 ck没有错
2024-01-10 07:13:44,309 - INFO: 13981 ck为空，重新获取ck并保存
2024-01-10 07:13:50,062 - INFO: 18015 ck为空，重新获取ck并保存
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1d5d2d5c00>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mclub.lenovo.com.cn', port=443): Max retries exceeded with url: /signlist/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1d5d2d5c00>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/arcadia/repo/marigold233_lenovo-sign/lenovo_sign.py", line 244, in <module>
    main()
  File "/arcadia/repo/marigold233_lenovo-sign/lenovo_sign.py", line 239, in main
    message += sign(session)
  File "/arcadia/repo/marigold233_lenovo-sign/lenovo_sign.py", line 178, in sign
    res = session.get(url="https://mclub.lenovo.com.cn/signlist/")
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mclub.lenovo.com.cn', port=443): Max retries exceeded with url: /signlist/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1d5d2d5c00>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by anonymous216041** [comment]
几台机器都是在获取CK 的时候就报错了，昨天晚上是获取完CK 报错，邪门

**Comment by anonymous216041** [comment]
找到问题所在
[message_push.Email_message]
sender_email = "xxx@163.com"
sender_password = "xxxaaabbb"
receiver_email = "bbb@163.com"
smtp_server = "smtp.163.com"
smtp_port = "465"
这部分要把示例的值取消掉，否则就是send email error (550, b'User has no permission')报错
至于抽风问题，还是那样，不定时抽风

**Comment by anonymous216041** [comment]
[message_push.Email_message]
sender_email = ""
sender_password = ""
receiver_email = ""
smtp_server = ""
smtp_port = ""

**Comment by marigold233** [comment]
> 178,

改下脚本里面的代码：
```diff
- res = session.get(url="https://mclub.lenovo.com.cn/signlist/")
+ res = session.get("https://mclub.lenovo.com.cn/sign")
```
再试试

**Comment by anonymous216041** [comment]
改不改，都一样一大堆代码，目前这个时段，测试了10次

**Comment by marigold233** [comment]
> 改不改，都一样一大堆代码，目前这个时段，测试了10次

你要不上华为云函数吧

**Comment by anonymous216041** [comment]
咋搞呢
